Attempt to use variables in runner tags

diff --git a/.gitlab/spack/ci.yaml b/.gitlab/spack/ci.yaml
--- a/.gitlab/spack/ci.yaml
+++ b/.gitlab/spack/ci.yaml
@@ -14,48 +14,34 @@ ci:
       before_script:
         - echo "This section cannot be empty because of Spack CI implementation."
 
-  - submapping:
-    - match:
-      - 'env.get("LCSCHEDCLUSTER", "") == "corona"'
-      build-job:
-        tags: [corona, shell]
-        script::
-        - export ALLOC_ID=$(flux jobs --name="${CORONA_ALLOC_NAME}" -n -o "{id}")
-        - echo -e "[Information] Shared allocation ID = ${ALLOC_ID}"
-        - export PROXY="$( [[ -n "${ALLOC_ID}" ]] && echo "flux proxy ${ALLOC_ID}" || echo "" )"
-        - ${PROXY} flux watch $( ${PROXY} flux batch -o output.stdout.type=kvs ${CORONA_JOB_ALLOC} .gitlab/spack/ci-script.sh)
-    - match:
-      - 'env.get("LCSCHEDCLUSTER", "") == "dane"'
-      build-job:
-        tags: [dane, shell]
-        script::
-        - export JOBID=$(squeue -h --name=${DANE_ALLOC_NAME} --format=%A)
-        - srun $( [[ -n "${JOBID}" ]] && echo "--jobid=${JOBID}" ) ${DANE_JOB_ALLOC} .gitlab/spack/ci-script.sh
-    - match:
-      - 'env.get("LCSCHEDCLUSTER", "") == "lassen"'
-      build-job:
-        tags: [lassen, shell]
-        script::
-        - lalloc ${LASSEN_JOB_ALLOC} .gitlab/spack/ci-script.sh
-    - match:
-      - 'env.get("LCSCHEDCLUSTER", "") == "tioga"'
-      build-job:
-        tags: [tioga, shell]
-        script::
-        - export ALLOC_ID=$(flux jobs --name="${TIOGA_ALLOC_NAME}" -n -o "{id}")
-        - echo -e "[Information] Shared allocation ID = ${ALLOC_ID}"
-        - export PROXY="$( [[ -n "${ALLOC_ID}" ]] && echo "flux proxy ${ALLOC_ID}" || echo "" )"
-        - ${PROXY} flux watch $( ${PROXY} flux batch -o output.stdout.type=kvs ${TIOGA_JOB_ALLOC} .gitlab/spack/ci-script.sh)
-    - match:
-      - 'env.get("LCSCHEDCLUSTER", "") == "tuolumne"'
-      build-job:
-        tags: [tuolumne, shell]
-        script::
-        - export ALLOC_ID=$(flux jobs --name="${TUOLUMNE_ALLOC_NAME}" -n -o "{id}")
-        - echo -e "[Information] Shared allocation ID = ${ALLOC_ID}"
-        - export PROXY="$( [[ -n "${ALLOC_ID}" ]] && echo "flux proxy ${ALLOC_ID}" || echo "" )"
-        - ${PROXY} flux watch $( ${PROXY} flux batch -o output.stdout.type=kvs ${TUOLUMNE_JOB_ALLOC} .gitlab/spack/ci-script.sh)
-    match_behavior: first
+  - build-job:
+    tags: [${LCSCHEDCLUSTER}, shell]
+    script::
+    - |
+      if ${LCSCHEDCLUSTER} == "corona" ; then
+        export ALLOC_ID=$(flux jobs --name="${CORONA_ALLOC_NAME}" -n -o "{id}")
+        echo -e "[Information] Shared allocation ID = ${ALLOC_ID}"
+        export PROXY="$( [[ -n "${ALLOC_ID}" ]] && echo "flux proxy ${ALLOC_ID}" || echo "" )"
+        ${PROXY} flux watch $( ${PROXY} flux batch -o output.stdout.type=kvs ${CORONA_JOB_ALLOC} .gitlab/spack/ci-script.sh)
+      elif ${LCSCHEDCLUSTER} == "dane" ; then
+        export JOBID=$(squeue -h --name=${DANE_ALLOC_NAME} --format=%A)
+        srun $( [[ -n "${JOBID}" ]] && echo "--jobid=${JOBID}" ) ${DANE_JOB_ALLOC} .gitlab/spack/ci-script.sh
+      elif ${LCSCHEDCLUSTER} == "lassen" ; then
+        lalloc ${LASSEN_JOB_ALLOC} .gitlab/spack/ci-script.sh
+      elif ${LCSCHEDCLUSTER} == "tioga" ; then
+        export ALLOC_ID=$(flux jobs --name="${TIOGA_ALLOC_NAME}" -n -o "{id}")
+        echo -e "[Information] Shared allocation ID = ${ALLOC_ID}"
+        export PROXY="$( [[ -n "${ALLOC_ID}" ]] && echo "flux proxy ${ALLOC_ID}" || echo "" )"
+        ${PROXY} flux watch $( ${PROXY} flux batch -o output.stdout.type=kvs ${TIOGA_JOB_ALLOC} .gitlab/spack/ci-script.sh)
+      elif ${LCSCHEDCLUSTER} == "tuolumne" ; then
+        export ALLOC_ID=$(flux jobs --name="${TUOLUMNE_ALLOC_NAME}" -n -o "{id}")
+        echo -e "[Information] Shared allocation ID = ${ALLOC_ID}"
+        export PROXY="$( [[ -n "${ALLOC_ID}" ]] && echo "flux proxy ${ALLOC_ID}" || echo "" )"
+        ${PROXY} flux watch $( ${PROXY} flux batch -o output.stdout.type=kvs ${TUOLUMNE_JOB_ALLOC} .gitlab/spack/ci-script.sh)
+      else
+        echo -e "[Error] Unsupported LCSCHEDCLUSTER='${LCSCHEDCLUSTER}'"
+        exit 1
+      fi
 
   - reindex-job:
       tags: [oslic, shell]
